gruppo/urls.py
from django.urls import path, include
from . import views

app_name = 'gruppo'
urlpatterns = [
   path('', views.home, name="home"),
   path('foto/', views.fotopage, name="foto"),
   path('video/', views.videopage, name="video"),
   path('chisiamo/', views.chisiamo, name='chisiamo'),
   path('lavoraconnoi/', views.lavoraconnoi, name="lavoraconnoi"),
   path('prenotaevento/', views.prenotaevento, name="prenotaevento"),
]

sitomusicale/urls.py
from django.contrib import admin
from django.urls import path, include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gruppo.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="it">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="DJoz Template">
    <meta name="keywords" content="DJoz, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DJoz | Template</title>
    
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/barfiller.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/nowfont.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/rockville.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/slicknav.min.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css">
    {% block style %}{% endblock style %}
</head>

<body>
<header class="header">
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2">
                <div class="header__logo">
                    <a href="{% url "gruppo:home" %}"><img src="{% static "img/logoCarlo.png" %}" width=500></a>
                </div>
            </div>
        
            <div class="col-lg-10 col-md-10">
                <div class="header__nav">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li><a href="{% url "gruppo:home" %}">Home</a></li>
                            <li><a href="{% url "gruppo:foto" %}">Foto</a></li>
                            <li><a href="{% url "gruppo:video" %}">Video</a></li>
                            <li><a href="{% url "gruppo:chisiamo" %}">Chi Siamo</a></li> 
                            <li><a href="{% url "gruppo:lavoraconnoi" %}">Lavora con Noi</a></li>
                            <li><a href="{% url "gruppo:prenotaevento" %}">Prenota Evento</a></li>                              
                            
                        </ul>
                    </nav>                        
                </div>
            </div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
</header>
   
   


    {% block content  %}
    
    
    {% endblock content  %}

    
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

    <!-- Footer Section Begin -->

    <footer class="footer spad set-bg" data-setbg="{% static "img/footer-bg.png" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer__address">
                        <ul>
                            <li>
                                <i class="fa fa-phone"></i>
                                <p>Numero</p>
                                <h6>(+39) 340 823 4506</h6>
                            </li>
                            <li>
                                <i class="fa fa-envelope"></i>
                                <p>Email</p>
                                <h6>Puppets.eventi@gmail.com</h6>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 offset-lg-1 col-md-6">
                    <div class="footer__social">
                        <h2>Puppets</h2>
                        <div class="footer__social__links">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6">
                    <div class="footer__newslatter">
                        <ul>
                            <li><a href="{% url "gruppo:home" %}">Home</a></li>
                            <li><a href="{% url "gruppo:foto" %}">Foto</a></li>
                            <li><a href="{% url "gruppo:video" %}">Video</a></li>
                            <li><a href="{% url "gruppo:chisiamo" %}">Chi Siamo</a></li> 
                            <li><a href="{% url "gruppo:lavoraconnoi" %}">Lavora con Noi</a></li>
                            <li><a href="{% url "gruppo:prenotaevento" %}">Prenota Evento</a></li>                                
                            
                        </ul>
                        
                    </div>
                </div>
            </div>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
			{% comment %} <div class="footer__copyright__text">
				<p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
			</div> {% endcomment %}
			<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </div>
    </footer>

    <!-- Footer Section End -->


    <!-- Js Plugins -->
    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
    <script src="{% static "js/jquery.nicescroll.min.js" %}"></script>
    <script src="{% static "js/jquery.barfiller.js" %}"></script>
    <script src="{% static "js/jquery.countdown.min.js" %}"></script>
    <script src="{% static "js/jquery.slicknav.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>

    <!-- Music Plugin -->
    <script src="{% static "js/jquery.jplayer.min.js" %}"></script>
    <script src="{% static "js/jplayerInit.js" %}"></script>
    {% block script %}

   
{% endblock script %}
</body>
</html>

templates/chisiamo.html
{% extends "base.html" %}
{% block title %}Chi Siamo{% endblock title %}

{% block content %}
<br><br>
<section class="youtube spad">

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="section-title center-title">
                <h2>Chi Siamo</h2>
                
            </div>
        </div>
    </div>
        {% for artista in artisti  %}
           
        <div class="row">
            <div class="col">                
                    <div class="card mb-3" style="max-width:auto;">
                        <div class="row no-gutters">
                        <div class="col-md-4">
                            <img class="rounded-circle" src="{{artista.img.url}}" alt="{{artista.id}}">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                            <h5 class="card-title">{{artista.nome}} {{artista.cognome}}</h5>
                            <p class="card-text">{{artista.esperienza}}</p>
                            <p class="card-text"><small class="text-muted">{{artista.strumento}}</small></p>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
        </div>
        {% comment %} {% else %}
        <div class="row">
                <div class="col">            
                        <div class="card mb-3" style="max-width:auto;">
                            <div class="row no-gutters">                
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">{{artista.nome}} {{artista.cognome}}</h5>
                                        <p class="card-text">{{artista.esperienza}}</p>
                                        <p class="card-text"><small class="text-muted">Suona il {{artista.strumento}}</small></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <img class="rounded-circle" src="{{artista.img.url}}" alt="...">
                                </div>
                            </div>
                        </div>
                    </div>                 
            </div>

            {% endif %}
            {% endfor %} {% endcomment %}
            {% endfor %}
        </div>
</div>

</section>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
{% endblock content %}

templates/fotopage.html
{% extends "base.html" %}
{% load static %}
{% block titolo %}Foto{% endblock titolo %}
{% block style %}
<style>
    div.discography__item__pic > img {
    width:360px;
    height:240px;
    object-fit: cover;
}
</style>  
{% endblock style %} 

{% block content %}
<section class="discography spad"> 
  
  <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title center-title">
                        <h2>Foto del Gruppo</h2>
                        
                    </div>
                </div>
            </div>
            <div class="row">
            {% for foto in foto %}
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="{{foto.img.url}}">
                        </div>
                    </div>                
                </div>
            {% endfor %}    
            </div>
    

    <br><br><br><br>
     
      
          <div class="row">            
                <div class="col-10">
              {% for commento in commenti %}
              <div class="alert bg-light mb-3" role="alert">
                <h4 class="card-title">{{commento.nome}}</h4>
                <h6 class="card-subtitle mb-2 text-muted">{{commento.email}}</h6>
                <p class="card-text">{{commento.commento}}.</p>
              </div>
              {% endfor %}
                </div>
                <div class="col-2">
                  Saluta la Band!
                  <form class="form-group" method="POST">
                      {% csrf_token %}
                      {{form.as_p}}
                      <button type="submit" class="btn btn-primary">Invia</button>
                </div>
            </div>
</div>

</section>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
{% endblock content %}
{% block script %}
<script>
    $(document).ready(function(){
    
    var array_images = document.querySelectorAll("div.discography__item__pic > img");
    var myVar;
    var contatore = 0;
    function scambia() {
        let seme = Math.floor(Math.random() * 1000);
        for (let i=0; i<seme; i++) {;}
        let array_random = [];
        let array_src = [];
        for (let i=0; i<array_images.length; i++) {
            let n = Math.floor(Math.random() * array_images.length);
            while (array_random.includes(n)) {
                n = Math.floor(Math.random() * array_images.length);
            }
            array_random.push(n);
            array_src.push(array_images[i].src);
        }
    
        for (let i=0; i<array_images.length; i++) {//alert(array_random[i]);
            array_images[i].src = array_src[array_random[i]];
        }
    }
    function showImage(){
        if (contatore > 10000) {
            contatore = 1;
        }
        /*if (contatore > 0) {
            $("div.discography__item__pic > img").fadeIn(1000);
        }*/
        else {
            $("div.discography__item__pic > img").fadeOut(200);
        }
    
        scambia();
        $("div.discography__item__pic > img").fadeIn(200);
        contatore++;
        //myVar = setTimeout(showImage, 3000);
    }
    //showImage();
        //setInterval(  scambiaClienti(); }, 5000);
        setInterval(showImage, 6000);
    });
    </script>
{% endblock script %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block style %}



{% endblock style %}
<style>
    .section.title puppets{
        background-image: url(static\img\header1.jpg) !important;
    }
    .section-title.puppets h1{
        font-size: 100px;
	    color: #040404;
	    font-family: "Rockville Solid Regular";
        background-color: red;

    }
</style>

{% block content %}
 <!-- Header Section Begin -->
 <header class="hero spad set-bg" data-setbg="{% static "img/puppets_finale.png" %}">
       
 </header>
 <!-- Header Section End -->
<!-- Event Section Begin carousel-->
<section class="event spad">
    <div class="container">        
         <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    
                </div>
            </div>
        </div> 
        
        <div class="row">
            
            <div class="event__slider owl-carousel">  
                {% for slide in slides  %}             
                <div class="col-lg-4">                    
                    <div class="event__item">                        
                        <div class="event__item__pic set-bg">                            
                            <div class="event__item__pic set-bg" data-setbg="{{ slide.img.url }}">
                                {% comment %} <div class="tag-date">
                                    <span>{{slide.data}}</span>
                                </div> {% endcomment %}
                            </div>
                        </div>
                        {% comment %} <div class="event__item__text">
                            <h4>{{slide.titolo}}</h4>
                            <p><i class="fa fa-map-marker"></i>{{slide.luogo}}</p>
                        </div>  {% endcomment %}
                                                
                    </div>                                      
                </div> 
                {% endfor %}               
            </div>            
        </div>        
    </div>   
</section> 


<div class="container">
<hr>
<br><br>
<div class="section-title center-title">
    <h1 class="puppets" style="color:black;font-family:"Rockville Solid Regular";font-size: 100px;">Puppets</h1>
</div>
<br><br><br><br>
<div style="font-size: ">
<p>Il gruppo Puppets è il partner perfetto per trasformare i tuoi eventi in esperienze memorabili. Nasce nel 2008 dall’idea degli amici e membri principali della band: Michela Corni, Roberto Verace, Edoardo Vezil e Giovanni Ranieri. Successivamente negli anni entreranno a far parte del gruppo anche gli altri membri, che ne faranno quello che è oggi: un gruppo musicale multiforme.                                     Con un vasto repertorio che spazia dalla disco anni 70, 80, 90 al jazz e pop-elettronico contemporaneo, la nostra musica è pensata per soddisfare tutti i gusti. Offriamo inoltre uno spettacolo coinvolgente e versatile, con esibizioni che variano da set acustici intimi, a performance elettrizzanti a balli scatenati con il nostro dj.   La nostra priorità è far sentire il pubblico parte integrante dello spettacolo!    
<br>
Siamo consapevoli dell'importanza dell'affidabilità e della professionalità in un evento per questo lavoriamo a stretto contatto con gli organizzatori per garantire una perfetta integrazione della nostra esibizione nell'ambito complessivo dell’evento. La band, infatti, vanta un'ampia esperienza in occasioni di ogni tipo, tra cui matrimoni, compleanni e serate in locali, creando atmosfere uniche e coinvolgenti, modellando il nostro repertorio per adattarlo al tema o alle esigenze specifiche del tuo evento. 
<br>
Siamo aperti a prenotazioni per eventi di ogni genere!. Collaboriamo con organizzatori, agenzie e privati per portare la nostra passione per la musica in ogni angolo del mondo degli eventi.
</p>

<a href="{% url "gruppo:chisiamo" %}">Chi Siamo...</a><hr>
</div>


</div>

<br/><br/><br/>
<!-- Event Section End -->
<div class="container">
    <h2>CALENDARIO EVENTI</h2>
    <br/><br/><br/>
    <div class="row">
        {% for evento in eventi  %}
        <div class="col-lg-3 col-md-6">            
            <div class="card shadow" style="width: 18rem;">
                <img src="{{evento.img.url}}" class="card-img-top" alt="{{evento.titolo}}">
                <div class="card-body">
                  <h5 class="card-title">{{evento.titolo}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted">{{evento.data}}</h6>
                  {% comment %} <p class="card-text">{{evento.descrizione}}</p> {% endcomment %}
                  <p class="card-text">{{evento.luogo}}</p>
                 
                </div>
              </div>                
        </div>
        {% endfor %}      
    </div>   
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

{% endblock content %}
{% block script %}
 <!-- Js Plugins -->
 <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
 <script src="{% static "js/bootstrap.min.js" %}"></script>
 <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
 <script src="{% static "js/jquery.nicescroll.min.js" %}"></script>
 <script src="{% static "js/jquery.barfiller.js" %}"></script>
 <script src="{% static "js/jquery.countdown.min.js" %}"></script>
 <script src="{% static "js/jquery.slicknav.js" %}"></script>
 <script src="{% static "js/owl.carousel.min.js" %}"></script>
 <script src="{% static "js/main.js" %}"></script>

 <!-- Music Plugin -->
 <script src="{% static "js/jquery.jplayer.min.js" %}"></script>
 <script src="{% static "js/jplayerInit.js" %}"></script>


{% endblock script %}

templates/lavoraconnoi.html
{% extends "base.html" %}
{% block title %}Lavora Con Noi{% endblock title %}
{% block style %}
<style>
  section {
      margin-top:35px;
      margin-bottom:35px;
  }
  .input_elem, #id_captcha_1 {
      height: 50px;
      font-size: 13px;
      color: #666666;
      padding-left: 20px;
      margin-bottom: 20px;
      border: 1px solid #e1e1e1;
  }
  #lbl_captcha {
      text-align:right;
      height:50px;
      line-height: 50px;
  }
  p.invalid-feedback {
      margin:-10px 0 10px 0;
      padding-left:5px;
  }
  p#errore_captcha {
      text-align:center;
  }
  </style>  

{% endblock style %}

{% block content %}
<br><br>
<section class="discography spad">

<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <div class="section-title center-title">
          <h2>Lavora Con Noi</h2>   
          <br>
          
          <div class="form-group">
            <form method="post" action="{% url "gruppo:lavoraconnoi" %}"> 
                  
              {% csrf_token %}              
              {{form.as_div}}
             
              <br>          
              <button type="submit" class="btn btn-primary">Invia</button>        
            </form>
         </div>
        </div>
    </div>
</div>
  
 
  
</section>



{% endblock content %}

  

templates/prenotaevento.html
{% extends "base.html" %}
{% block title %}Prenota Evento{% endblock title %}
{% block style %}
<style>
  section {
      margin-top:35px;
      margin-bottom:35px;
  }
  .input_elem, #id_captcha_1 {
      height: 50px;
      font-size: 13px;
      color: #666666;
      padding-left: 20px;
      margin-bottom: 20px;
      border: 1px solid #e1e1e1;
  }
  #lbl_captcha {
      text-align:right;
      height:50px;
      line-height: 50px;
  }
  p.invalid-feedback {
      margin:-10px 0 10px 0;
      padding-left:5px;
  }
  p#errore_captcha {
      text-align:center;
  }
  </style>   
{% endblock style %}

{% block content %}
<br><br>
<section class="youtube spad">
    
   
     <!-- Contact Section Begin -->
     <section class="contact spad">
      <div class="container">
          <div class="row">
              <div class="col-lg-4">
                  <div class="contact__address">
                      <div class="section-title">
                          <h2>Contatti</h2>
                      </div>
                      <p>Puoi chiamarci al telefono o scriverci per e-mail: ti risponderemo al più presto!</p>
                      <ul>
                          <li>
                              <i class="fa fa-phone"></i>
                              <h5>Cellulare</h5>
                              <span>1-677-124-44227</span>
                          </li>
                          <li>
                              <i class="fa fa-envelope"></i>
                              <h5>Email</h5>
                              <p>puppets.eventi@gmail.com</p>
                          </li>
                      </ul>
                  </div>
              </div>

    <div class="container">
      <div class="col-lg-8">
        <div class="contact__form">
            <div class="section-title">
                <h2>Prenota il tuo evento</h2>
            </div>
      <form method="post" action="{% url "gruppo:prenotaevento" %}">
        {% csrf_token %}
        {% csrf_token %}
        {% if messaggio %}
          <p class="text-success">{{ messaggio }}</p>
        {% endif %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="text-danger">{{error}}</div>
            {% endfor %}
            <br>
        {% endif %}
        <fieldset>
          <legend>Dati Personali</legend>
          <div class="form-row">
              <div class="col-md-6">
                  <!--<input class="form-control input_elem" type="text" placeholder="Nome">-->
                  {{ form.nome_cliente }}
                  {% for error in form.nome_cliente.errors  %}
                  <p class="invalid-feedback  d-block">{{error}}</p>
                  {% endfor %}
              </div>
              <div class="col-md-6">
                <!--<input class="form-control input_elem" type="text" placeholder="Cognome">-->
                {{ form.cognome_cliente }}
                {% for error in form.cognome_cliente.errors  %}
                <p class="invalid-feedback  d-block">{{error}}</p>
                {% endfor %}
            </div>
            <div class="col-md-6">
              <!--<input class="form-control input_elem" type="email" placeholder="Email">-->
              {{ form.email }}
              {% for error in form.email.errors  %}
              <p class="invalid-feedback  d-block">{{error}}</p>
              {% endfor %}
            </div>
            <div class="col-md-6">
              <!--<input class="form-control input_elem" type="text" placeholder="Città">-->
              {{ form.citta }}
              {% for error in form.citta.errors  %}
              <p class="invalid-feedback  d-block">{{error}}</p>
              {% endfor %}
            </div>
            <div class="col-md-6">
              <!--<input class="form-control input_elem" type="text" placeholder="Sigla della provincia">-->
              {{ form.provincia }}
              {% for error in form.provincia.errors  %}
              <p class="invalid-feedback  d-block">{{error}}</p>
              {% endfor %}
            </div>
            <div class="col-md-6">
              <!--<input class="form-control input_elem" type="text" placeholder="Cellulare (solo cifre, senza spazi)">-->
              {{form.telefono}}
              {% for error in form.cellulare_contatto.errors  %}
              <p class="invalid-feedback  d-block">{{error}}</p>
              {% endfor %}
            </div>
          </div>
        </fieldset>
        <fieldset>
          <legend>Dati per l'Evento</legend>
          <div class="form-row">
              <div class="col-md-12">
                  <!--<input type="text" class="form-control input_elem" id="tipo_evento" placeholder="Tipo di evento (matrimonio, compleanno,...)">-->
                  {{ form.tipo_evento }}
                  {% for error in form.tipo_evento.errors  %}
                  <p class="invalid-feedback  d-block">{{error}}</p>
                  {% endfor %}
              </div>
              <div class="col-md-12">
                <!--<input type="text" class="form-control input_elem" id="nome_luogo" placeholder="Nome della sala o del luogo privato">-->
                {{ form.luogo }}
                {% for error in form.luogo_evento.errors  %}
                <p class="invalid-feedback  d-block">{{error}}</p>
                {% endfor %}
            </div>
            <div class="col-md-6">
              <!--<input class="form-control input_elem" id="citta_evento" type="text" placeholder="Città">-->
              {{ form.citta_evento }}
              {% for error in form.citta_evento.errors  %}
              <p class="invalid-feedback  d-block">{{error}}</p>
              {% endfor %}
          </div>
            <div class="col-md-6">
                <!--<input class="form-control input_elem" id="provincia_evento" type="text" placeholder="Sigla della provincia">-->
                {{ form.prov_evento}}
                {% for error in form.provincia_evento.errors  %}
                <p class="invalid-feedback  d-block">{{error}}</p>
                {% endfor %}
            </div>
            <div class="col-md-12">
                <!--<input class="form-control input_elem" id="indirizzo_evento" type="text" placeholder="Via/Piazza e numero civico">-->
                {{ form.indirizzo_evento }}
                {% for error in form.indirizzo_evento.errors  %}
                <p class="invalid-feedback  d-block">{{error}}</p>
                {% endfor %}
            </div>
            <div class="form-group col-md-6">
                <!--<select id="inputState" id="componenti_evento" class="form-control input_elem">
                    <option selected>Partecipanti della band all'evento</option>
                    <option>...</option>
                  </select>-->
                  <label for="componenti">Partecipanti della band all'evento*</label>
                  {{ form.seleziona_artista }}
                  {% for error in form.componenti.errors  %}
                    <p class="invalid-feedback  d-block">{{error}}</p>
                  {% endfor %}
            </div>
            <div class="form-group col-md-6">
                <!--<input class="form-control input_elem" id="data_evento" type="date">-->
                <label for="data_evento">Data dell'evento*</label>
                {{ form.data_evento }}
                {% for error in form.data_evento.errors  %}
                <p class="invalid-feedback  d-block">{{error}}</p>
                {% endfor %}
            </div>
        </div>
    </fieldset>
              <div class="form-row">
                  <div id="lbl_captcha" class="col-md-6">
                      <label  for="captcha">Scrivi i caratteri che vedi*</label>
                  </div>
                  <div class="col-md-6">
                      {{ form.captcha }}
                  </div>
                  {% if form.captcha.errors %}
                      {% for error in form.captcha.errors %}
                          <p id="errore_captcha" class="invalid-feedback  d-block"><strong>{{ error|escape }}</strong></p>
                      {% endfor %}
                  {% endif %}
              </div>
              <br>
              <button type="submit" class="site-btn">PRENOTA L'EVENTO</button>
      </form>
    </div>
  </div>
</div>
</div>
<br><br>

</section>

{% endblock content %}

templates/videopage.html
{% extends "base.html" %}
{% load static %}
{% block title %}Video{% endblock title %}

{% block content %}
<br><br>
<!-- Youtube Section Begin -->
    <section class="youtube spad">
        
        <div class="container">
            <div class="row">                
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Video Del Gruppo</h2>
                        
                    </div>
                </div>
            </div>
            <div class="row">
                {% for video in video  %}
                <div class="col-lg-4 col-md-6 col-sm-6">                    
                    <div class="youtube__item">
                        <div class="youtube__item__pic set-bg" data-setbg="{{video.img.url}}">
                            <a href="{{video.link}}" class="play-btn video-popup"><i class="fa fa-play"></i></a>
                        </div>
                        <div class="youtube__item__text">
                            <h4>{{video.nome}}</h4>
                        </div>
                    </div>
                </div>  
                {% endfor %}              
            </div> 
    


    <br><br><br><br>
   
        
        <div class="row">            
          <div class="col-10">
            {% for commento in commenti %}
            <div class="alert bg-light mb-3" role="alert">
              <h4 class="card-title">{{commento.nome}}</h4>
              <h6 class="card-subtitle mb-2 text-muted">{{commento.email}}</h6>
              <p class="card-text">{{commento.commento}}.</p>
            </div>
        {% endfor %}
          </div>
          <div class="col-2">
            Saluta la Band!
            <form class="form-group" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Invia</button>
          </div>
        </div>
    </div>

</section> 
<!-- Youtube Section End -->
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
{% endblock content %}